### ISSUE TITLE
Purview Deploy Error Message

### ISSUE THREAD

**Issue by MicrosoftMcCormick** [microsoft/Data-and-AI-Strategy-Platform#36]
I don't seem to be able to create a branch, so putting this here. 

The Purview deployment error message when the Purview name is already in use is incorrect. It refers to the MLWorkspaceKeyVaultName key, which is a cut & paste error from the check above it. 

Needs to be updated to reflect that this is the Purview name which is already in use. 

File: .github/workflows/deployment_environment.yml
Line: 330

![image](https://github.com/microsoft/Data-and-AI-Strategy-Platform/assets/167103466/6dffd9ab-6d6f-4b2b-b616-51ec42ed4d91)

**Comment by hschwarz1** [comment]
@MicrosoftMcCormick I fixed this. Also, the token issue you're having should also be fixed. Please refresh your fork.
